### ISSUE TITLE
画像

### ISSUE THREAD

**Issue by krystalmm** [team-initialM/NaganoCake#87]
<img width="1440" alt="スクリーンショット 2021-03-24 15 59 34" src="https://user-images.githubusercontent.com/71312197/112268995-2310ab00-8cbb-11eb-938a-d36307e08915.png">

**Comment by akasatan** [comment]
![Uploading スクリーンショット 2021-03-24 15.59.34.png…]()

**Comment by akasatan** [comment]
<img width="1440" alt="スクリーンショット 2021-03-24 15 59 34" src="https://user-images.githubusercontent.com/76617776/112269024-2efc6d00-8cbb-11eb-90ca-4580a1d27070.png">

**Comment by krystalmm** [comment]
画像添付完了
